dist: trusty
sudo: required
addons:
  apt:
    packages:
    - google-chrome-stable
language: node_js
node_js:
- stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get install oracle-java8-set-default
before_script:
- webdriver-manager update
- nohup webdriver-manager start &
services: mongodb
env:
  global:
  - GOOGLE_CALLBACK=http://gains-app.herokuapp.com/auth/google/callback
  - S3_BUCKET=gains-test
  - secure: kLeRq5ThGCj46d2IpoCqsYddSz7kk6ThyI6XwglWxh8Q6gKqB3YtPbYl7cPjoOhcM+s3+RwK08u4DS0fl3P3gTHEUZmz0zQK0vKG5r9I7/LIsXW8Bmqs/Q7h5sN0Ezr5nNKJ3p9N6RNLR3IKcdAORz2H3wt5SW3XwGeIjDciWKspjkTHyseRvdE4VrS2h3N9/h8tC2RZ5mhmFgsnQm1YkPlaLWT9vYeUqR1U/TS8ph5uSvWzPspKWsV+VUsKTERTT86prf66L2GYiBbU/7fjvTld0FF1SvfWKfxExKQ3gEghNgpSvk4GGU7cukM7q+6odLW3pPOTt7N2ilzHq9NLr8EaG4hxekc7zlX/yg0Ov0+GBXY89TXzRd4YmWlKWEMPJ55/to+bbSGwvIX4c/1lexHaFjq9CYup2Ajfa8tDQAJ9qEpf3Mzjx5TlUXnNsFCWhk6J9FFrMBrOJhm7sMmncHn9cXpJwJ7/gHxwgZKWl2IiGpbaNBbEGn7FmuxqTx66S3BwjluPRXdZXP5KZ/0KIiDPsEgr3s+/SwCakd8e0HKb3h2Rf1bNEfndcyTAon98IYJGoUjhqemc4inE2DxaW6JWDu2ej2sS0Q/JFmpanRow7vM4VPRvTNQtDe9F2edjuGRiLQo9/I5xU+U+htB8HHXil8SV1i+V8ez2th5J0Kw=
  - secure: ggslUNWQE1egLwmf2ZuZDDIN3C+BuPoSN7TtESDIHD4jy7sciRa9lR/KTppA+fthyGfxfjxhvHWh/WEvi32l/vhaeMm/yhGRCYbCWe0cv7bqx364gXXuRDcw5e+QFioqXkl++v05x/9HALddqFpAvHCgEwh3emoIT8qFqNelDB61/yPbmSvcPJyZ07xSF998mmc+cXNqj32uuIzMf0SHMmZUxCRqGNc57NskoLMIo/D8rhyeAfYQbM6gcNNpf3ptoWXYTZye7QzPS23IKzQT8nmU8FyC9bhBEKldpaSB9/RO82f6AdZkQdNdA7F3f1avw4O9S4xTActG4Nj69ounHn6axqTMv/NCb3s5QqjMeQWHRJJUKe1rRqN+9HZzUsjPVtzZwSKQ27QhvppnaZgKQauywcymLQV+21L3olkjwpBYcKlpNGuAlQZ0SLGNoX6S9pNJ51w9UKRXl0wNGKBWE6WTDQ3UBdxVjulC36oMWWCnliW7xyDUYTQcdxaU+gCcGGeDTZqBgRHQ/LFcakHnPVXNdazCoa68JAHvhr76sZ+0wwa6gytcbmVGQtlAndTuxdXt4yQ/nBiFp8VXlCtAov8K4BlbXF2L8F13fS0/cvknaDaXm+JFZanPihxO1geJZ2mf8t8UERTexHXjx6RKbNgFfep8ALLaFLwK30KJP1E=
script:
- npm run unit
- npm run e2e
